In [13]:
import pickle
import pandas as pd

In [2]:
with open('../../dutta/entity_type.pickle', 'rb') as file:
    entity_type = pickle.load(file)

In [4]:
len(entity_type)

47294597

In [11]:
len(entity_type.values())

47294597

In [12]:
len(entity_type.keys())

47294597

In [18]:
type_df = pd.DataFrame()
type_df['qid'] = entity_type.keys()
type_df['type'] = entity_type.values()

In [20]:
type_df = type_df.astype(str)

In [21]:
type_df

qid                              type
0          Q5688836              b'television series'
1          Q5688837                  b'solar eclipse'
2          Q5688847                  b'solar eclipse'
3          Q5688849                         b'single'
4          Q5688853                          b'human'
5          Q5688861                  b'solar eclipse'
6          Q5688873                       b'painting'
7          Q5688878                  b'solar eclipse'
8          Q5688885                          b'album'
9          Q5688892                  b'solar eclipse'
10         Q5688895                  b'solar eclipse'
11         Q5688912                  b'solar eclipse'
12         Q5688913                  b'solar eclipse'
13         Q5688918              b'compilation album'
14         Q5688924                  b'solar eclipse'
15         Q5688925  b'Wikimedia disambiguation page'
16         Q5688929             b'television program'
17         Q5688935      b'television series episode'
18         Q5688937                  b'solar eclipse'
19         Q5688938                           b'film'
20         Q5688951      b'television series episode'
21         Q5688955                          b'human'
22         Q5688963                           b'book'
23         Q5688986                  b'solar eclipse'
24         Q5688990                  b'solar eclipse'
25         Q5689000                  b'solar eclipse'
26         Q5689010                  b'solar eclipse'
27         Q5689016                          b'human'
28         Q5689111                  b'extended play'
29         Q5689116                  b'solar eclipse'
...             ...                               ...
47294567    Q918448                                 -
47294568    Q440991                                 -
47294569    Q333130                                 -
47294570  Q18110151                                 -
47294571  Q18170994                                 -
47294572  Q27616433                                 -
47294573   Q4758632                                 -
47294574    Q247574                                 -
47294575   Q1468175                                 -
47294576  Q16252860                                 -
47294577   Q7233235                                 -
47294578  Q16895200                                 -
47294579    Q458304                                 -
47294580   Q2714542                                 -
47294581   Q1191869                                 -
47294582   Q5594001                                 -
47294583   Q1187518                                 -
47294584   Q7157064                                 -
47294585  Q19022408                                 -
47294586   Q1404061                                 -
47294587     Q43173                                 -
47294588   Q5190170                                 -
47294589   Q1515524                                 -
47294590  Q24886846                                 -
47294591   Q7247985                                 -
47294592    Q979217                                 -
47294593    Q626368                                 -
47294594   Q5510883                                 -
47294595   Q5124643                                 -
47294596  Q25039503                                 -

[47294597 rows x 2 columns]

In [16]:
type_df_grouped = type_df.groupby(['type']).size()

In [17]:
type_df_grouped

type
b'"I Want" song'                                                                                                                                                                                                    1
b'"mixed union"'                                                                                                                                                                                                   42
b"''glorieta''"                                                                                                                                                                                                     1
b"'Hyposmochoma'"                                                                                                                                                                                                  62
b"'Ndrina"                                                                                                                                 

In [20]:
import torch
import torch.nn.functional as F

In [21]:
a = torch.rand(2, 3, 4)
b = torch.rand(2, 3, 6)
a = F.pad(a, (0, b.size(2) - a.size(2)), 'constant', 0)

In [22]:
test = F.relu(torch.bmm(a.view(2 * 3, 6, 1), b.view(2 * 3, 1, 6)))
test = test.view(2, 3, 6, 6)
test_t = test.transpose(3, 2)

In [23]:
test.size()

torch.Size([2, 3, 6, 6])

In [24]:
test

tensor([[[[ 0.0076,  0.0087,  0.0073,  0.0073,  0.0222,  0.0226],
          [ 0.0861,  0.0987,  0.0832,  0.0823,  0.2527,  0.2561],
          [ 0.2294,  0.2630,  0.2217,  0.2194,  0.6731,  0.6823],
          [ 0.2036,  0.2336,  0.1969,  0.1948,  0.5977,  0.6058],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

         [[ 0.2902,  0.2949,  0.2045,  0.0052,  0.0314,  0.1245],
          [ 0.2665,  0.2708,  0.1878,  0.0048,  0.0289,  0.1143],
          [ 0.0831,  0.0844,  0.0585,  0.0015,  0.0090,  0.0356],
          [ 0.0437,  0.0444,  0.0308,  0.0008,  0.0047,  0.0188],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

         [[ 0.1357,  0.1701,  0.1658,  0.1997,  0.1577,  0.0478],
          [ 0.5762,  0.7223,  0.7042,  0.8482,  0.6697,  0.2032],
          [ 0.5095,  0.6387,  0.6227,  0.7500,  0.5922,  0.1797],
      

In [25]:
test_t

tensor([[[[ 0.0076,  0.0861,  0.2294,  0.2036,  0.0000,  0.0000],
          [ 0.0087,  0.0987,  0.2630,  0.2336,  0.0000,  0.0000],
          [ 0.0073,  0.0832,  0.2217,  0.1969,  0.0000,  0.0000],
          [ 0.0073,  0.0823,  0.2194,  0.1948,  0.0000,  0.0000],
          [ 0.0222,  0.2527,  0.6731,  0.5977,  0.0000,  0.0000],
          [ 0.0226,  0.2561,  0.6823,  0.6058,  0.0000,  0.0000]],

         [[ 0.2902,  0.2665,  0.0831,  0.0437,  0.0000,  0.0000],
          [ 0.2949,  0.2708,  0.0844,  0.0444,  0.0000,  0.0000],
          [ 0.2045,  0.1878,  0.0585,  0.0308,  0.0000,  0.0000],
          [ 0.0052,  0.0048,  0.0015,  0.0008,  0.0000,  0.0000],
          [ 0.0314,  0.0289,  0.0090,  0.0047,  0.0000,  0.0000],
          [ 0.1245,  0.1143,  0.0356,  0.0188,  0.0000,  0.0000]],

         [[ 0.1357,  0.5762,  0.5095,  0.1250,  0.0000,  0.0000],
          [ 0.1701,  0.7223,  0.6387,  0.1567,  0.0000,  0.0000],
          [ 0.1658,  0.7042,  0.6227,  0.1528,  0.0000,  0.0000],
      

In [26]:
F.max_pool1d(test[0], 6).squeeze(2)

tensor([[ 0.0226,  0.2561,  0.6823,  0.6058,  0.0000,  0.0000],
        [ 0.2949,  0.2708,  0.0844,  0.0444,  0.0000,  0.0000],
        [ 0.1997,  0.8482,  0.7500,  0.1840,  0.0000,  0.0000]])

In [27]:
F.max_pool2d(test_t, (6, 1)).squeeze(2)

tensor([[[ 0.0226,  0.2561,  0.6823,  0.6058,  0.0000,  0.0000],
         [ 0.2949,  0.2708,  0.0844,  0.0444,  0.0000,  0.0000],
         [ 0.1997,  0.8482,  0.7500,  0.1840,  0.0000,  0.0000]],

        [[ 0.3243,  0.2285,  0.1077,  0.4650,  0.0000,  0.0000],
         [ 0.7861,  0.4154,  0.9043,  0.2271,  0.0000,  0.0000],
         [ 0.0166,  0.8000,  0.6972,  0.1169,  0.0000,  0.0000]]])

In [28]:
max_pool_a = F.max_pool2d(test_t, (6, 1)).squeeze(2)
max_pool_b = F.max_pool2d(test, (6, 1)).squeeze(2)

In [29]:
a = F.max_pool1d(max_pool_a, max_pool_a.size(2)).squeeze(2)

In [30]:
a

tensor([[ 0.6823,  0.2949,  0.8482],
        [ 0.4650,  0.9043,  0.8000]])

In [31]:
F.softmax(a, 1)

tensor([[ 0.3498,  0.2374,  0.4128],
        [ 0.2532,  0.3929,  0.3539]])